--Measures exploration 

--find the total sales
select sum(sales_amount) as total_sales from gold.fact_sales

--find how many items are sold 
select sum(quantity) as total_items_sold from gold.fact_sales

--find the average selling price
select avg(price) as avg_price from gold.fact_sales

--find the total number of orders
select count(distinct order_number) as total_orders from gold.fact_sales

--find the total number of products
select count(distinct product_number) as total_products from gold.dim_products

--find the total number of customers
select count(customer_number) as total_customers from gold.dim_customers
  
--find the total number of customers that has placed an order
select count( distinct customer_number) as total_customers 
from gold.dim_customers cu
left join gold.fact_sales sa 
on cu.customer_key = sa.customer_key

--Generate a report that shows all key metrics of the business 
select 'Total sales' as measure_name, sum(sales_amount) as measure_value from gold.fact_sales
union all 
select 'Total quantity' as measure_name, sum(quantity) as measure_value from gold.fact_sales
union all 
select 'Avg price' as measure_name, avg(price) as measure_value from gold.fact_sales
union all 
select 'Total orders' as measure_name, count(distinct order_number) as measure_value from gold.fact_sales
union all 
select 'Total products' as measure_name, count(distinct product_number) as measure_value from gold.dim_products
union all 
select 'Total customers' as measure_name, count(distinct customer_number) as measure_value from gold.dim_customers

--Magnitude(combane the measure values by categries)

--find total customers by countries
select country,count(customer_key) as total_customers 
from gold.dim_customers
group by country
order by total_customers desc

--find total customers by gender
select gender,count(customer_key) as total_customers 
from gold.dim_customers
group by gender
order by total_customers desc

--find total products by category
select category,count(product_key) as total_products 
from gold.dim_products
group by category
order by total_products desc

--what is the average costs in each category?
select category, avg(cost) as avg_costs
from gold.dim_products
group by category
order by avg_costs desc 

--what is the total revenue generated for each category?
select sum(f.sales_amount)as total_revenue, p.category
from gold.fact_sales f 
left join gold.dim_products p 
on p.product_key=f.product_key
group by p.category
order by total_revenue desc

--what is the total revenue is generated by each customer?
select  
c.customer_key,
c.first_name,
c.last_name,
sum(f.sales_amount)as total_revenue
from gold.fact_sales f 
left join gold.dim_customers c 
on c.customer_key=f.customer_key
group by 
c.customer_key,
c.first_name,
c.last_name
order by total_revenue desc

--what is the distribution of sold items across countries?
select  
c.country,
count(s.quantity) as distribution_sold_items
from gold.fact_sales s
left join gold.dim_customers c 
on c.customer_key=s.customer_key
group by c.country
order by distribution_sold_items desc 


